### ISSUE TITLE
Bug display

### ISSUE THREAD

**Issue by Devlop-er** [Wikiki/bulma-switch#27]
Hi I know an issue has been opened and closed already but I get the same bug,

The stylesheet is linked and here is my code :

<div class="field">
                <input id="switchRoundedDefault" type="checkbox" name="switchRoundedDefault" class="switch is-rounded" checked="checked">
                <label for="switchRoundedDefault">Switch rounded default</label>
              </div>
            
What's the problem thanks ^^

<img width="251" alt="Capture d’écran 2019-03-29 à 17 50 11" src="https://user-images.githubusercontent.com/46845666/55248924-23e8e080-524b-11e9-80cc-37ffdfc1579b.png">

**Comment by Wikiki** [comment]
Hi,

On which browser are you working ?

**Comment by Devlop-er** [comment]
I'm using Chrome(latest version)

**Comment by cwise** [comment]
Same issue

**Comment by ddreier** [comment]
Same thing here, FWIW. Just downloaded bulma-switch, using bulma v0.7.4 and Chrome v73.

**Comment by Wikiki** [comment]
I'll have a look on it and I'll keep you in touch.

**Comment by campZero** [comment]
Can confirm, using Firefox 66.0.3 (64bit) and bulma 0.7.4

**Comment by Baennon** [comment]
Same issue here on Chrome

**Comment by Baennon** [comment]
I resolved it by renaming the .min.css file to .css. Don't know why though.

**Comment by alevv** [comment]
same problem here, anyone figured it out? I used both Chrome and Safari

**Comment by okas** [comment]
Same problem. Chrome 74.0.3729.108 (Build oficial) (64 bits)

**Comment by solomon77** [comment]
same problem.
fixed it this way.

index.sass L14:L16
```
$paddle-height: calc($switch-height - ($switch-paddle-offset * 2))
$paddle-width: calc($switch-height - ($switch-paddle-offset * 2))
$paddle-active-offest: cacl($switch-width - $paddle-width - ($switch-paddle-offset * 1.5))
```
↓
```
$paddle-height: $switch-height - ($switch-paddle-offset * 2)
$paddle-width: $switch-height - ($switch-paddle-offset * 2)
$paddle-active-offest: $switch-width - $paddle-width - ($switch-paddle-offset * 1.5)
```

'cacl'...:open_mouth:

**Comment by JollyGrin** [comment]
Also have the same error

![image](https://user-images.githubusercontent.com/28109194/57587215-cf9b7680-7501-11e9-8cbc-4b4c038f8561.png)

On Bulma 0.7.4

**Comment by murilobd** [comment]
Just submitted the #28 with fix from the mistyped `cacl` word

**Comment by Wikiki** [comment]
Hi,

Thanks @murilobd it's merged.
I'll update npm before the end of the week

**Comment by gauravat16** [comment]
I am still facing the issue on Bulma 0.7.5.  I got the minified file from master branch dist folder.

**Comment by mosesontheweb** [comment]
Hi,

I'm using Bulma 0.7.5 and I'm facing problems in displaying the switch button correctly. For some reason I can see warnings at label::after in my inspector:
```
top: .75rem-calc($switch-height - ($switch-paddle-offset * 2))/2;
width: calc($switch-height - ($switch-paddle-offset * 2));
height: calc($switch-height - ($switch-paddle-offset * 2));
```
They're all striked through, so the sliding button won't show up. Demo site is working pretty well. It seems that the SASS file is not properly compiled to CSS. I investigates the original SASS file, for some reason I can't see the corresponding lines ... 

Any ideas why?

Many thanks in advance, regards, Thomas

**Comment by BarGillNVLab** [comment]
Same problem - latest versions of Chrome, bulma and npm - and switches just switch the color, without that nice animation :)

**Comment by BarGillNVLab** [comment]
> same problem.
> fixed it this way.
> 
> index.sass L14:L16
> 
> ```
> $paddle-height: calc($switch-height - ($switch-paddle-offset * 2))
> $paddle-width: calc($switch-height - ($switch-paddle-offset * 2))
> $paddle-active-offest: cacl($switch-width - $paddle-width - ($switch-paddle-offset * 1.5))
> ```
> 
> ↓
> 
> ```
> $paddle-height: $switch-height - ($switch-paddle-offset * 2)
> $paddle-width: $switch-height - ($switch-paddle-offset * 2)
> $paddle-active-offest: $switch-width - $paddle-width - ($switch-paddle-offset * 1.5)
> ```
> 
> 'cacl'...

Could you explaion a little bit more?
Thanks in advance
Efi

**Comment by julio-gorge** [comment]
Broken for me on Chrome 75.0.3770.100 (Win10) too!

**Comment by MakRatanakKh** [comment]
Yeah, I have the same issue here.
![image](https://user-images.githubusercontent.com/46364520/61194329-e40b1380-a6ea-11e9-8cd6-de5e2d815b89.png)

**Comment by Belgian93** [comment]
Was using bulma-extensions and had the same issue, "solved" by using the specific bulma-switch package found here: [bulma-switch](https://www.npmjs.com/package/bulma-switch).

Seems there is a little version mismatch between the bundled extensions and the individual component.

**Comment by zhukovsergei** [comment]
![image](https://user-images.githubusercontent.com/1946769/65877463-088e9780-e38c-11e9-9fcd-b44dabb2c3b8.png)
same here.
Latest Google chrome, I tried both bulma-switch.min.css compiled form this repo and installed via npm (both are different). Both way gives this view

**Comment by Nonononoki** [comment]
Same problem here: Chrome 78 and Bulma 0.8.0. 
Workaround: Use earlier version: https://raw.githubusercontent.com/Wikiki/bulma-switch/d642b75531958f6c6e9401e12912244f12d78dba/dist/css/bulma-switch.min.css

**Comment by fspring** [comment]
> Was using bulma-extensions and had the same issue, "solved" by using the individual bulma-switch package found here: [bulma-switch](https://www.npmjs.com/package/bulma-switch).
> 
> Seems there is a little version mismatch between the bundled extensions and the individual component.

That also worked for me. Using the bulma-extensions package resulted in the error described here.

**Comment by iplanwebsites** [comment]
Thanks for the PR - had this issue as well today.

**Comment by faroukfaiz10** [comment]
> Same problem here: Chrome 78 and Bulma 0.8.0.
> Workaround: Use earlier version: https://github.com/Wikiki/bulma-switch/blob/8c20fa23fbc697d70a2e3d886c872a328afab202/dist/css/bulma-switch.min.css

This resolved it for me!

**Comment by greenhost87** [comment]
> Same problem here: Chrome 78 and Bulma 0.8.0.
> Workaround: Use earlier version: https://github.com/Wikiki/bulma-switch/blob/8c20fa23fbc697d70a2e3d886c872a328afab202/dist/css/bulma-switch.min.css

Also work for me

**Comment by doc-han** [comment]
The problem here is that. Whoever did run the last build for bulma-switch.min.css made an error of having uncompiled sass in CSS
